[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.commitizen]
version = "{{ cookiecutter.version }}"
tag_format = "v$major.$minor.$patch$prerelease"
version_files = [
    "{{ cookiecutter.project_slug }}/__init__.py",
    "setup.cfg",
]
